export enum HttpStatusCode {
    Continue = 100,                    // 100 - Continuer
    SwitchingProtocols = 101,          // 101 - Changement de protocoles
    Processing = 102,                  // 102 - Traitement en cours
    EarlyHints = 103,                  // 103 - Indications précoces
    Ok = 200,                          // 200 - OK
    Created = 201,                     // 201 - Créé
    Accepted = 202,                    // 202 - Accepté
    NonAuthoritativeInformation = 203, // 203 - Information non autorisée
    NoContent = 204,                   // 204 - Pas de contenu
    ResetContent = 205,                // 205 - Contenu réinitialisé
    PartialContent = 206,              // 206 - Contenu partiel
    MultiStatus = 207,                 // 207 - Multi-Statuts
    AlreadyReported = 208,             // 208 - Déjà rapporté
    ImUsed = 226,                      // 226 - Je suis utilisé
    MultipleChoices = 300,             // 300 - Choix multiples
    MovedPermanently = 301,            // 301 - Déplacé de façon permanente
    Found = 302,                       // 302 - Trouvé
    SeeOther = 303,                    // 303 - Voir ailleurs
    NotModified = 304,                 // 304 - Non modifié
    UseProxy = 305,                    // 305 - Utiliser un proxy
    Unused = 306,                      // 306 - Non utilisé
    TemporaryRedirect = 307,           // 307 - Redirection temporaire
    PermanentRedirect = 308,           // 308 - Redirection permanente
    BadRequest = 400,                  // 400 - Requête incorrecte
    Unauthorized = 401,                // 401 - Non autorisé
    PaymentRequired = 402,             // 402 - Paiement requis
    Forbidden = 403,                   // 403 - Interdit
    NotFound = 404,                    // 404 - Non trouvé
    MethodNotAllowed = 405,            // 405 - Méthode non autorisée
    NotAcceptable = 406,               // 406 - Non acceptable
    ProxyAuthenticationRequired = 407, // 407 - Authentification proxy requise
    RequestTimeout = 408,              // 408 - Temps d'attente de la requête écoulé
    Conflict = 409,                    // 409 - Conflit
    Gone = 410,                        // 410 - Parti
    LengthRequired = 411,              // 411 - Longueur requise
    PreconditionFailed = 412,          // 412 - Échec de la précondition
    PayloadTooLarge = 413,             // 413 - Charge utile trop importante
    UriTooLong = 414,                  // 414 - URI trop long
    UnsupportedMediaType = 415,        // 415 - Type de média non supporté
    RangeNotSatisfiable = 416,         // 416 - Plage non satisfaisable
    ExpectationFailed = 417,           // 417 - Échec de l'attente
    ImATeapot = 418,                   // 418 - Je suis une théière
    MisdirectedRequest = 421,           // 421 - Requête mal dirigée
    UnprocessableEntity = 422,         // 422 - Entité non traitable
    Locked = 423,                      // 423 - Verrouillé
    FailedDependency = 424,            // 424 - Dépendance échouée
    TooEarly = 425,                     // 425 - Trop tôt
    UpgradeRequired = 426,              // 426 - Mise à niveau requise
    PreconditionRequired = 428,         // 428 - Précondition requise
    TooManyRequests = 429,              // 429 - Trop de requêtes
    RequestHeaderFieldsTooLarge = 431,  // 431 - Champs d'en-tête de requête trop grands
    UnavailableForLegalReasons = 451,   // 451 - Indisponible pour des raisons légales
    InternalServerError = 500,          // 500 - Erreur interne du serveur
    NotImplemented = 501,               // 501 - Non implémenté
    BadGateway = 502,                   // 502 - Passerelle incorrecte
    ServiceUnavailable = 503,           // 503 - Service indisponible
    GatewayTimeout = 504,               // 504 - Temps d'attente de la passerelle écoulé
    HttpVersionNotSupported = 505,     // 505 - Version HTTP non supportée
    VariantAlsoNegotiates = 506,        // 506 - La variante négocie également
    InsufficientStorage = 507,          // 507 - Stockage insuffisant
    LoopDetected = 508,                 // 508 - Boucle détectée
    NotExtended = 510,                  // 510 - Non étendu
    NetworkAuthenticationRequired = 511, // 511 - Authentification réseau requise
}
